// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl5FFP2YXSGFiRvKOXCFFtI7dIix9EaNM',
    appId: '1:629885936331:web:05c6920077e497943af14e',
    messagingSenderId: '629885936331',
    projectId: 'smart-scheduling-engine',
    authDomain: 'smart-scheduling-engine.firebaseapp.com',
    databaseURL: 'https://smart-scheduling-engine-default-rtdb.firebaseio.com',
    storageBucket: 'smart-scheduling-engine.firebasestorage.app',
    measurementId: 'G-EYTRV5SVXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JP_3RASUTEqA-4m3lq1Sh5sC9YI8peo',
    appId: '1:629885936331:android:104db181c56de66d3af14e',
    messagingSenderId: '629885936331',
    projectId: 'smart-scheduling-engine',
    databaseURL: 'https://smart-scheduling-engine-default-rtdb.firebaseio.com',
    storageBucket: 'smart-scheduling-engine.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl5FFP2YXSGFiRvKOXCFFtI7dIix9EaNM',
    appId: '1:629885936331:web:cd0f109e0d6891c83af14e',
    messagingSenderId: '629885936331',
    projectId: 'smart-scheduling-engine',
    authDomain: 'smart-scheduling-engine.firebaseapp.com',
    databaseURL: 'https://smart-scheduling-engine-default-rtdb.firebaseio.com',
    storageBucket: 'smart-scheduling-engine.firebasestorage.app',
    measurementId: 'G-JPYDRH200N',
  );
}
